import type { Metadata } from "next";
import {  Zilla_Slab, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/generalUI/Header";
import FloatingMenu from "@/components/generalUI/FloatingMenu";

const zillaSlab = Zilla_Slab({
  variable: "--font-zilla",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"]
});
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"]
});



export const metadata: Metadata = {
  title: "Barraca Producciones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${zillaSlab.variable} antialiased relative`}
      >
        <Header />
        {/* <FloatingMenu /> */}
        {children}
      </body>
    </html>
  );
}
